// =============================================================================
//  site.config.ts — THE ONLY FILE YOU EDIT TO MAKE THIS PORTFOLIO YOURS
// =============================================================================
//
//  It's all writing and data — no code to change. Edit a value below, run
//  `npm run build`, and it's on your site. No JSX, no className, no imports to
//  chase. Look for the `CUSTOMIZE:` notes next to the values you'll most likely
//  want to change.
//
//  WHAT'S IN HERE (scan the section banners to jump around):
//    • Identity      — site name + canonical URL
//    • About         — hero snapshot, bio paragraphs, tagline, closing quote
//    • Experience    — the career timeline
//    • Gear          — the photography kit
//    • Services      — the "things I build and make" list
//    • Socials       — social links + contact email
//    • Writing       — the essay manifest (bodies live in content/writing/*.mdx)
//    • Projects      — design projects + web/software projects
//    • Previews      — which items each homepage surface shows (curation)
//    • Section copy  — the inline headings, sublines, nav labels + page ledes
//
//  TWO THINGS INTENTIONALLY LIVE ELSEWHERE (generated / structural, not copy):
//    • data/photos.ts  — auto-generated by `npm run sync-gallery`; don't hand-edit
//    • data/motifs.ts  — the decorative-flower SVG registry (see MANUAL-TODO §7)
//
//  See the "Make it yours" section of README.md for the full three-step guide.
// =============================================================================

// -----------------------------------------------------------------------------
// IDENTITY  (was data/site.ts)
// -----------------------------------------------------------------------------
// Canonical site identity — single source of truth for absolute URLs used by
// metadata (metadataBase / canonical / OG), sitemap.ts, robots.ts, and JSON-LD.
// CUSTOMIZE: if the production domain ever changes, change it here only.
export const SITE_URL = "https://charlieramus.com";
export const SITE_NAME = "Charlie Ramus";

// -----------------------------------------------------------------------------
// ABOUT  (was data/about.ts)
// -----------------------------------------------------------------------------
// Bio — the machine-readable half of ABOUT-CHARLIE.md. Reconciled in V2 from the
// current charlieramus.com copy + the newer "About Charlie" dump into one voice:
// dry and precise, letting the specifics carry it (Charlie's call, V2 Stage 1).

// Structured hero/about fields, so V3 can render name/location/roles without
// parsing prose. The hero shows `name`; `roles` feed the about + any chips.
export interface Snapshot {
  name: string;
  location: string;
  roles: string[];
}

// CUSTOMIZE: name is the hero headline (Charlie chose his name over a tagline).
export const snapshot: Snapshot = {
  name: "Charlie Ramus",
  location: "Boulder, Colorado",
  roles: ["Creator"],
};

// Source for the "Behind the pixels" about section. Newest framing first: the
// solo full-product builder, then the arc that got there, then off the screen.
// `aboutParagraphs[0]` is the teaser shown by default; the rest sit behind the
// "read more" toggle (components/about-bio.tsx). Paragraph 2 was tightened in V8
// Stage 3 so the expanded bio no longer restates the Ostiara career-timeline
// entry verbatim — it keeps only the discovery insight the timeline doesn't have.
// CUSTOMIZE: edit copy freely — types don't care how long each paragraph is.
export const aboutParagraphs: string[] = [
  "I'm a high school junior in Boulder and a self-taught developer who builds full products solo, backend architecture, the design system, and the marketing copy in between. I work mostly in Next.js, TypeScript, and Tailwind, with Claude Code as a regular collaborator.",
  "Most of my time right now goes to Ostiara. The part that stuck with me wasn't the code but the customer discovery, talking to door-to-door reps surfaced a real split between menu-priced and measure-on-site quoting, and that split changes what the tool owes each group.",
  "Before Ostiara there were e-commerce stores that never took off but taught me business, and years of building architecture content on platforms that grew into a global community of builders and passed 300,000+ impressions. Alongside Ostiara I keep smaller builds moving — VaultDNA, MyLifeInARepo, and this site itself.",
  "Off the screen I shoot on a Canon EOS R5 (with a photo credit at Boulder Reporting Lab), climb, ski, and ride gravel bikes. I read and journal. Lots of ideas are still queued, I plan to keep building and sharing the journey.",
];

// SEO <meta> description + any social card. NOT the hero headline (that's the
// name) — this is the one-sentence summary that describes the site. CUSTOMIZE.
export const tagline =
  "Charlie Ramus, a self-taught developer in Boulder building full products solo, from backend to design system to shipped copy.";

// The big serif line that closes the page (finale flower grid). Charlie's thesis,
// in his own framing — echoes the about copy ("backend architecture, the design
// system, and the marketing copy in between"). `\n` marks the line break.
// CUSTOMIZE: swap for any closing line you like; the flowers stay decorative.
export const finaleQuote =
  "A portfolio is not proof of what you built. It is proof you noticed.";

// -----------------------------------------------------------------------------
// EXPERIENCE  (was data/experience.ts)
// -----------------------------------------------------------------------------
// Experience / career — single source of truth. Seeded from the current site.
// Newest-first. To add a role: copy an entry, fill the CUSTOMIZE fields.

export type ExperienceLink = { label: string; href: string };

export type Experience = {
  /** CUSTOMIZE: date range string shown as-is, e.g. "2026 — Present" */
  dates: string;
  /** CUSTOMIZE: position / role name */
  title: string;
  /** CUSTOMIZE: company or org name ("" hides it) */
  org: string;
  /** CUSTOMIZE: org link URL ("" hides the arrow icon) */
  href: string;
  /** CUSTOMIZE: reference links, or [] */
  links: ExperienceLink[];
  /** CUSTOMIZE: 2-4 sentence description of what you did and learned */
  description: string;
  /** CUSTOMIZE: skill tag strings */
  tags: string[];
  /** Single-letter mark for the timeline chip. Defaults to org/title initial. */
  logo?: string;
  /** Timeline chip background — a theme token, e.g. "var(--color-blue)". */
  logoBg?: string;
  /** Timeline chip letter color. */
  logoFg?: string;
  /** Numeric start year (vertical timeline placement). */
  start?: number;
  /** Numeric end year; null = present. */
  end?: number | null;
};

export const entries: Experience[] = [
  {
    dates: "2026 — Present",
    title: "Stealth Startup (Ostiara)",
    org: "",
    href: "",
    links: [{ label: "GitHub", href: "https://github.com/charlieramus/ostiara" }],
    description:
      "Building Ostiara solo, end to end: a SaaS platform for door-to-door sales teams across home-service verticals — pest control, solar, roofing, fencing, security. Shipped the marketing site, an admin dashboard, and a teams-and-roles system on Clerk Organizations with Supabase row-level security, all wearing a design system I built for it. Ran customer-discovery interviews to learn how reps actually quote prices on a doorstep.",
    tags: ["Next.js", "TypeScript", "Marketing", "Full Stack", "Design Systems", "Customer Discovery"],
    logo: "S",
    logoBg: "var(--color-blue)",
    logoFg: "var(--color-paper)",
    start: 2026,
    end: null,
  },
  {
    dates: "2026 — Present",
    title: "TA & Media Manager (Seasonal)",
    org: "Liberty Puzzles",
    href: "https://libertypuzzles.com/pages/about-us",
    links: [],
    description:
      "Puzzle assembly and customer tours for a high-end puzzle company. Managed social accounts, created content, and engaged the puzzle community.",
    tags: ["Photography", "Videography", "Lightroom", "Visual Storytelling"],
    logo: "L",
    logoBg: "var(--color-red)",
    logoFg: "var(--color-paper)",
    start: 2026,
    end: null,
  },
  {
    dates: "2025 — Present",
    title: "Content Creator & Builder",
    org: "",
    href: "",
    links: [],
    description:
      "Built an architecture-building community on Roblox (Bloxburg): designed and shared original builds that passed 300,000+ views, produced tutorial content, and grew a global audience of fellow builders. Started as genuine enjoyment and became an exercise in showing up consistently.",
    tags: ["Community Building", "Content Creation", "Figma", "3D Modeling"],
    logo: "C",
    logoBg: "var(--color-yellow)",
    logoFg: "var(--color-ink)",
    start: 2025,
    end: null,
  },
];

// -----------------------------------------------------------------------------
// GEAR  (was data/gear.ts)
// -----------------------------------------------------------------------------
// Photography gear. Seeded from the current site. CUSTOMIZE names/notes/links.

export type GearItem = {
  name: string;
  /** short note, e.g. "Primary body" ("" hides) */
  note: string;
  /** manufacturer/retailer URL ("" hides link) */
  href: string;
};

export const gear: Record<string, GearItem[]> = {
  bodies: [
    { name: "Canon EOS R5", note: "Primary body", href: "https://www.bhphotovideo.com/c/product/1547009-REG/canon_4147c002_eos_r5_mirrorless_camera.html/?ap=y&ap=y&smp=y&smp=y&store=420&lsft=BI%3A6879&gad_source=1&gad_campaignid=21076579605&gbraid=0AAAAAD7yMh0-OFrE43zjBuUbJxSYRsB-k&gclid=Cj0KCQjwsMLSBhD9ARIsAIpUTDrsOvxuYPfYhgujaOTr7umJ6ZcT5SYAY8oEGm4llxfsHFITBwXFmPEaAvPAEALw_wcB" },
    { name: "DJI Air 2s Combo", note: "Primary drone (Look at 3s for current pricing options", href: "https://www.bhphotovideo.com/c/product/1632435-REG/dji_cp_ma_00000354_01_air_2s_drone.html" },
  ],
  lenses: [
    { name: "Canon RF 24-105mm f/4", note: "", href: "https://www.bhphotovideo.com/c/product/1433712-REG/canon_rf_24_105mm_f_4l_is.html" },
    { name: "Sigma 150-600mm f/5.6-6.3", note: "", href: "https://www.keh.com/shop/sigma-150-600mm-f-5-6-3-dg-os-hsm-c-contemporary-lens-for-canon-ef-mount-95-1.html?aid=369805-2306724&nbt=nb%3Aadwords%3Ag%3A23090482546%3A186818604415%3A777581404268&nb_adtype=pla&nb_kwd=&nb_ti=pla-58923981526&nb_mi=7115600&nb_pc=online&nb_pi=369805-2306724&nb_ppi=58923981526&nb_placement=&nb_li_ms=&nb_lp_ms=&nb_fii=&nb_ap=&nb_mt=&gad_source=1&gad_campaignid=23090482546&gbraid=0AAAAAD_vFQvaBTCE9BTS2TOimjO0p2iiS&gclid=Cj0KCQjwsMLSBhD9ARIsAIpUTDq26MkxhwO3mS4Vc4fLGkW9Xze1NC7UK9MTz898uBRUXVeiOgPwxZwaAiYJEALw_wcB" },
  ],
  bags: [
    { name: "Kiboko V2.0 30L+", note: "Long travel / high capacity", href: "https://www.bhphotovideo.com/c/product/1751846-REG/gura_gear_gg0533_1945_kiboko_2_0_30l_backpack.html/?ap=y&ap=y&smp=y&smp=y&store=420&smpm=ba_f2_lar&lsft=BI%3A6879&gad_source=1&gad_campaignid=20000463050&gbraid=0AAAAAD7yMh2suwTirxA6MJn2Zkdb2Rg6j&gclid=Cj0KCQjwsMLSBhD9ARIsAIpUTDpGE_4bJEwCx7pe5jlzrBEFc_EbeLDpQ-UYwbbQ4uWmuhfXCvaLe8MaAkviEALw_wcB" },
    { name: "Thule Aspect V2", note: "Everyday carry", href: "https://www.thule.com/en-am/backpacks/camera-backpacks-bags/thule-aspect-dslr-backpack-_-tl_85854238717" },
  ],
  accessories: [
    { name: "Carbon-fiber tripod", note: "", href: "https://www.bhphotovideo.com/c/product/1709952-REG/k_f_concept_kf09_094v1_carbon_fiber_tripod.html" },
    { name: "Deity V-Mic D4 Mini", note: "", href: "https://www.bhphotovideo.com/c/product/1654686-REG/deity_microphones_v_mic_d4_mini_ultracompact.html" },
  ],
};

export const gearSections: { key: keyof typeof gear; label: string }[] = [
  { key: "bodies", label: "Camera Bodies" },
  { key: "lenses", label: "Lenses" },
  { key: "bags", label: "Bags" },
  { key: "accessories", label: "Accessories" },
];

// -----------------------------------------------------------------------------
// SERVICES  (was data/services.ts)
// -----------------------------------------------------------------------------
// The "Services" section list. Reframed in V2 from the mockup's for-hire agency
// copy ("I've got your back with… / connect with your users") into an honest
// capabilities/toolkit list — Charlie is a solo builder, not an agency. Every
// item traces to real work in the other data files (Ostiara stack, the Notion/
// Spotify design work, the Canon R5 + drone kit, the essays, the Roblox community).
//
// Shape matches components/services.tsx exactly (a flat string[] rendered one per
// .svc-grid cell), so V3 swaps the inline `SERVICES` array for `import { services }`.
// The grid is 3 columns; 9 items keeps the mockup's 3×3. CUSTOMIZE freely.

/** Section heading + subhead (CUSTOMIZE — replaces the mockup's for-hire copy). */
export const servicesHeading = "Things I build and make";
export const servicesSub =
  "Full products end to end, the engineering, the design system, and the story around them.";

/** One label per .svc-grid cell. Keep to multiples of 3 for the grid. */
export const services: string[] = [
  "Full-product builds",
  "Next.js / TypeScript",
  "Design systems",
  "Brand & identity",
  "Marketing design",
  "Photography",
  "Drone / aerial",
  "Technical writing",
  "Content & community",
];

// -------------------------------f----------------------------------------------
// SOCIALS  (was data/socials.ts)
// -----------------------------------------------------------------------------
// Social links — single source of truth (data only; icons live in the component
// layer). Seeded from the current site. CUSTOMIZE handles/links.

export type Social = {
  /** display label */
  label: string;
  href: string;
  /** @handle or username, optional */
  handle?: string;
  /** which account, for the two Instagrams */
  note?: string;
};

export const socials: Social[] = [
  {
    label: "LinkedIn",
    href: "https://www.linkedin.com/in/charlie-ramus-776366398/",
  },
  { label: "GitHub", href: "https://github.com/charlieramus", handle: "charlieramus" },
  {
    label: "Instagram",
    href: "https://www.instagram.com/chahramii/",
    handle: "@chahramii",
    note: "photography",
  },
  {
    label: "Instagram",
    href: "https://www.instagram.com/charlieramus_/",
    handle: "@charlieramus_",
    note: "personal",
  },
  { label: "Letterboxd", href: "https://letterboxd.com/cwramus/", handle: "cwramus" },
];

// CUSTOMIZE: preferred contact for the "Get in touch" CTA.
export const contactEmail = "charlie.ramus12@gmail.com";

// -----------------------------------------------------------------------------
// WRITING  (was data/writing.ts)
// -----------------------------------------------------------------------------
// Writing manifest — the ordering contract for V3's "Latest writing" list, so the
// homepage never has to parse MDX frontmatter at render time. Each `slug` MUST
// match a file in content/writing/<slug>.mdx exactly (the slug is the route:
// /writing/[slug]). `title`/`date` mirror that file's frontmatter for display —
// keep them in sync when you edit an essay. Lower `order` = newer = shown first.
//
// The full frontmatter contract V4's /writing/[slug] route reads:
//   title · date · author · headerImage ("" = no header) · externalLink · externalLinkLabel

export type WritingEntry = {
  /** matches content/writing/<slug>.mdx and the /writing/[slug] route */
  slug: string;
  /** mirrors the MDX `title` frontmatter */
  title: string;
  /** mirrors the MDX `date` frontmatter (display string) */
  date: string;
  /** sort key for the "Latest writing" list — 1 = newest, shown first */
  order: number;
};

export const writing: WritingEntry[] = [
  {
    slug: "the-hobby-hexagon-is-a-trap",
    title: "The Hobby Hexagon Is a Trap (And I Built One Anyway)",
    date: "July 2026",
    order: 1,
  },
  {
    slug: "when-bigger-means-more-biased",
    title:
      "When Bigger Means More Biased: How Scale Transforms LLMs into Confident Amplifiers of Majority Perspectives",
    date: "May 2026",
    order: 2,
  },
  {
    slug: "the-third-rotation",
    title: "The Third Rotation",
    date: "May 2026",
    order: 3,
  },
  {
    slug: "architecture-of-self-justification",
    title: "The Architecture of Self-Justification: How Pride Disguises Moral Failure",
    date: "December 2025",
    order: 4,
  },
];

// -----------------------------------------------------------------------------
// DESIGN PROJECTS  (was data/projects-design.ts)
// -----------------------------------------------------------------------------
// Design work. Seeded from the current site (descriptions verbatim). Image arrays
// live in /public and are wired in V4 — CUSTOMIZE paths then.

export type DesignProject = {
  /** CUSTOMIZE: project name */
  title: string;
  /** CUSTOMIZE: year */
  date: string;
  /** CUSTOMIZE: description */
  description: string;
  /** CUSTOMIZE: image paths in /public (added V4) */
  images?: string[];
  /** shared aspect ratio (w/h) of this project's slides — drives the frame so
   *  slides render un-cropped. Slides within a project are uniform. */
  ratio?: number;
  /** CUSTOMIZE: how many slides show before the "Show all" toggle; default 2.
   *  Leave unset to use the default. Projects with fewer slides than this hide
   *  the toggle entirely. */
  previewCount?: number;
};

export const designProjects: DesignProject[] = [
  {
    title: "Notion Brand Pitch",
    date: "2025",
    description:
      "A 10-slide brand strategy pitch for Notion built as a class project. Covers a full brand audit, problem framing, target market, competitive landscape, repositioning strategy, and a new visual identity concept. Produced all in Figma.",
    ratio: 16 / 9,
    images: [
      "/images/design/notion/01-Titlemp4.webp",
      "/images/design/notion/02-Brand-Auditmp4.webp",
      "/images/design/notion/03-The-Problemmp4.webp",
      "/images/design/notion/04-Target-Marketmp4.webp",
      "/images/design/notion/05-Competitor-Landscapemp4.webp",
      "/images/design/notion/06-New-Positioningmp4.webp",
      "/images/design/notion/07-New-Identitymp4.webp",
      "/images/design/notion/08-Feature-AI-Agentsmp4.webp",
      "/images/design/notion/09-Feature-Mail-and-Calendarmp4.webp",
      "/images/design/notion/10-Financialsmp4.webp",
    ],
  },
  {
    title: "Spotify IMC Campaign",
    date: "2025",
    description:
      "A 6-panel integrated marketing communications poster board for Spotify, developed for a high school marketing course. Covers campaign strategy, target audience, creative direction, media planning, and budget allocation. This one I wouldve perfered to be longer but at the end of the day the assignment was to make a 6 panel poster board so I did that.",
    ratio: 1.477,
    images: [
      "/images/design/spotify/IMC-6-Slide-Poster-Board1mp4.webp",
      "/images/design/spotify/IMC-6-Slide-Poster-Board2mp4.webp",
      "/images/design/spotify/IMC-6-Slide-Poster-Board3mp4.webp",
      "/images/design/spotify/IMC-6-Slide-Poster-Board4mp4.webp",
      "/images/design/spotify/IMC-6-Slide-Poster-Board5mp4.webp",
      "/images/design/spotify/IMC-6-Slide-Poster-Board6mp4.webp",
    ],
  },
  {
    title: "Photography Presentation UI",
    date: "2024",
    description:
      "Presentation UI designed around personal travel photography sets. Built in Figma to explore editorial layout, typography-forward design, and how to let images carry the visual weight of a slide.",
    ratio: 9 / 16,
    images: [
      "/images/design/photography-ui/florida-1.webp",
      "/images/design/photography-ui/florida-2.webp",
      "/images/design/photography-ui/florida-3.webp",
      "/images/design/photography-ui/bvi.webp",
    ],
  },
];

// -----------------------------------------------------------------------------
// WEB PROJECTS  (was data/projects-web.ts)
// -----------------------------------------------------------------------------
// Web / software projects. Expanded in V2 from ABOUT-CHARLIE.md §4 + Side
// Projects (what each is + the hard part). Ordered: flagship first, then
// spotlight picks, then the long tail. `spotlight` marks the featured tier so
// V3 can build a "highlights" surface without relying on array position alone.
// Screenshots (`image`) are authored in V4.

export type WebProject = {
  /** CUSTOMIZE: project name */
  title: string;
  /** CUSTOMIZE: the URL segment for this project's detail page —
   *  `/web-projects/<slug>`. Stable + URL-safe, required (titles can carry dots
   *  like "charlieramus.comv2", so slugs are explicit, not derived). */
  slug: string;
  /** CUSTOMIZE: year or range (some are approximate — confirm) */
  date: string;
  /** CUSTOMIZE: 1-3 sentences — what it is + the hard part */
  description: string;
  /** CUSTOMIZE: live/repo link ("" hides) */
  href: string;
  /** CUSTOMIZE: tech tags */
  tags: string[];
  /** CUSTOMIZE: true = featured/"highlights" tier (V3 reads this). */
  spotlight?: boolean;
  /** CUSTOMIZE: screenshot path in /public (the /web-projects list thumbnail +
   *  the detail-page OG fallback when no heroShot is set). */
  image?: string;

  // ---------------------------------------------------------------------------
  //  CASE STUDY (V11/V12) — the screenshot-forward detail page at
  //  /web-projects/<slug>. Every field below is OPTIONAL: a section renders
  //  ONLY when its backing field is present and non-empty, in this fixed order.
  //  A project with none of these still renders a clean page from the fields
  //  above (title / date / tags / description). Author them per project here.
  // ---------------------------------------------------------------------------
  /** CUSTOMIZE: full-width rounded main screenshot (a /public path). Top of the
   *  case study; also the preferred OG image (falls back to `image`). */
  heroShot?: string;
  /** CUSTOMIZE: the "Project Overview" facts card. Each row is optional and is
   *  skipped when empty; `timeline` / `stack` / `link` fall back to the
   *  project's own `date` / `tags` / `href` when their field is omitted. */
  overview?: {
    /** e.g. "Solo — full stack + design" */
    role?: string;
    /** defaults to project.date if omitted */
    timeline?: string;
    /** defaults to project.tags if omitted; rendered as .tag chips */
    stack?: string[];
    /** e.g. "Shipped", "In progress" */
    status?: string;
    /** defaults to project.href if omitted; rendered as the external link */
    link?: string;
  };
  /** CUSTOMIZE: the "What I worked on" card — a freeform paragraph. */
  worked?: string;
  /** CUSTOMIZE: the "The Challenge" card — a freeform paragraph. */
  challenge?: string;
  /** CUSTOMIZE: the flower-bulleted process timeline. Each entry is a bold
   *  stage `title` + an optional one-line `detail`. Any length; the section is
   *  hidden when the array is empty/absent. */
  process?: { title: string; detail?: string }[];
  /** CUSTOMIZE: two side-by-side square images (/public paths). */
  squares?: [string, string];
  /** CUSTOMIZE: a full-content-width rounded screenshot (like the hero) that
   *  sits between the two square rows (/public path). Renders after `squares`,
   *  before `squares2`. */
  midShot?: string;
  /** CUSTOMIZE: a second pair of side-by-side square images, after the
   *  mid shot and still before the article (/public paths). */
  squares2?: [string, string];
  /** CUSTOMIZE: the editorial "article" block — body paragraphs + an
   *  optional pull-quote. */
  article?: { paragraphs: string[]; pullQuote?: string };
  /** CUSTOMIZE: a second full-width screenshot (/public path). */
  wideShot?: string;
  /** CUSTOMIZE: the closing banner — an optional image and/or text. */
  banner?: { image?: string; text?: string };
};

export const webProjects: WebProject[] = [
  {
    title: "Ostiara",
    slug: "ostiara",
    date: "May 2026 - Present",
    description:
      "A SaaS platform for door-to-door sales teams across home-service verticals, pest control, solar, roofing, fencing, security. Built solo end to end: marketing site, admin dashboard, and a teams-and-roles system on Clerk Organizations with Supabase row-level security. The hard part was customer discovery. Reps split between fixed-price menus and measure-on-site quoting, and that split changes what the tool owes each group.",
    href: "https://github.com/charlieramus/ostiara",
    tags: ["Next.js", "TypeScript", "Clerk", "Supabase", "Design Systems"],
    spotlight: true,
    // CUSTOMIZE: case-study content for /web-projects/ostiara. Timeline, Stack,
    // and Link are omitted here on purpose — they fall back to date/tags/href.
    // CUSTOMIZE (V11): full-width rounded hero screenshot. PLACEHOLDER — no real
    // Ostiara hero capture exists yet; reuses an existing /images/web shot so
    // the reference exercises every section end to end. Swap when captured.
    heroShot: "/images/web/charlieramus-com.webp",
    overview: {
      role: "Solo — full stack + design",
      status: "In progress",
    },
    worked:
      "Everything end to end: the marketing site, an admin dashboard, and a teams-and-roles system built on Clerk Organizations with Supabase row-level security — all wearing a design system I built for it. The backend data model, the UI, and the copy in between.",
    challenge:
      "The hard part wasn't the code — it was customer discovery. Talking to door-to-door reps surfaced a real split between fixed-price menus and measure-on-site quoting, and that split changes what the tool owes each group.",
    process: [
      {
        title: "Customer discovery",
        detail:
          "Interviewed door-to-door reps to learn how they actually quote a job on a doorstep.",
      },
      {
        title: "Data model & access control",
        detail:
          "Teams and roles on Clerk Organizations, with Supabase row-level security drawing the boundaries.",
      },
      {
        title: "Admin dashboard",
        detail: "The day-to-day surface managers and reps run the team from.",
      },
      {
        title: "Design system",
        detail: "Built one for the product and wore it across every surface.",
      },
      {
        title: "Marketing site",
        detail: "Shipped the public site and the copy around the product.",
      },
    ],
    // CUSTOMIZE (V12): two side-by-side square images. PLACEHOLDER — no true
    // square Ostiara screenshots exist yet; these two existing /images/web
    // shots are cropped to square via object-fit so the section renders in
    // review. Swap for real square Ostiara assets when captured.
    squares: ["/images/web/mylifeinarepo.webp", "/images/web/charlieramus-com.webp" ],
    // CUSTOMIZE: a full-width rounded screenshot between the two square rows.
    // PLACEHOLDER — reuses an existing /images/web shot; swap or remove.
    midShot: "/images/web/mylifeinarepo.webp",
    // CUSTOMIZE: a second pair of squares after the mid shot, before the
    // article. PLACEHOLDER — reuses the existing shots; swap or remove.
    squares2: ["/images/web/charlieramus-com.webp", "/images/web/mylifeinarepo.webp"],
    // CUSTOMIZE (V12): the editorial article — clean serif paragraphs with a
    // drop-cap on the first one and one optional large pull-quote.
    article: {
      paragraphs: [
        "Ostiara started as a platform for door-to-door sales teams across home-service verticals — pest control, solar, roofing, fencing, security — and I built the whole of it solo: the marketing site, an admin dashboard, and a teams-and-roles system on Clerk Organizations with Supabase row-level security drawing the boundaries. The data model, the interface, and the copy in between all wear a design system I built for the product.",
        "The part that stuck with me wasn't the code. It was the customer discovery. Talking to reps who actually quote jobs on a doorstep surfaced a real split I hadn't planned for: some verticals price off a fixed menu, and others have to measure the site before they can quote at all. That one distinction changes what the tool owes each group — what a rep needs on the screen when a homeowner is standing right there.",
        "So the build kept bending back to that split. Access control, the dashboard, the way a quote gets assembled — each decision had to hold for both the menu-priced teams and the measure-on-site ones, without forcing either into the other's workflow. The engineering was the straightforward half; keeping the product honest to how the work is really done was the rest of it.",
      ],
      pullQuote:
        "The hard part wasn't the code. It was learning how a rep actually quotes a job on a doorstep.",
    },
    // CUSTOMIZE (V12): a second full-width rounded screenshot. PLACEHOLDER — no
    // real Ostiara wide shot exists yet; reuses an existing /images/web shot so
    // the beat renders in review. Swap for a real Ostiara capture when available.
    wideShot: "/images/web/charlieramus-com.webp",
    // CUSTOMIZE (V12): the closing banner — an optional background image and/or
    // an overlaid line of text. Here it's text over an image (a subtle scrim is
    // added automatically for legibility). PLACEHOLDER image — reuses an
    // existing /images/web shot until a real Ostiara banner asset exists.
    banner: {
      image: "/images/web/charlieramus-com.webp",
      text: "Built solo, end to end — and still bending back to how the work is really done.",
    },
  },
  {
    title: "MyLifeInARepo",
    slug: "mylifeinarepo",
    date: "May 2026 - June 2026",
    description:
      "A personal life-tracking system built as a git repo of daily markdown files, parsed into structured data and rendered through a Next.js dashboard. Includes a financial module for net worth, budgeting, and cash-flow forecasting, plus a bank-statement import pipeline and a transaction-categorization engine modeled on how Monarch Money handles rule-based categorization. The hard part: turning freeform daily notes into reliable structured data. I still contribute to it occasionally but it is mostly done.",
    href: "",
    tags: ["Next.js", "TypeScript", "Markdown", "Personal Finance"],
    spotlight: true,
    image: "/images/web/mylifeinarepo.webp",
  },
  {
    title: "Querryn",
    slug: "querryn",
    date: "December 2025 - January 2026",
    description:
      "A Chrome extension that rates the credibility of sources for students writing academic papers, using a tiered domain-trust system, and exports citations in MLA, APA, Chicago, and BibTeX. Submitted to the Chrome Web Store.",
    href: "",
    tags: ["Chrome Extension", "TypeScript", "EdTech"],
  },
  {
    title: "VaultDNA",
    slug: "vaultdna",
    date: "April 2026 - May 2026",
    description:
      "An Obsidian plugin that encodes a personal knowledge base into synthetic DNA sequences, built around real DNA-storage constraints like homopolymer-run limits and GC-content biasing. Scoped as a quick one-to-two-week build alongside Ostiara.",
    href: "",
    tags: ["Obsidian Plugin", "TypeScript", "Biotech"],
  },
  {
    title: "charlieramus.comv2",
    slug: "charlieramus-com",
    date: "May 2026 — Present",
    description:
      "This site — a personal portfolio in Next.js, TypeScript, and Tailwind, with MDX for writing and a masonry photography grid backed by a fullscreen lightbox.",
    href: "https://charlieramus.com",
    tags: ["Next.js", "TypeScript", "Tailwind", "MDX"],
    image: "/images/web/charlieramus-com.webp",
  },
  {
    title: "Backtrace",
    slug: "backtrace",
    date: "July 2026 - August 2026",
    description:
      "An honest field instrument for reasoning about where a wildland fire started. You walk the burn with a map, flag physical fire-pattern indicators, and record the direction each one points. Backtrace fuses those bearings, each with its own angular uncertainty into a probability field for the origin: a heatmap with credible regions, not a single false-precision dot.",
    href: "https://github.com/charlieramus/backtrace",
    tags: ["HTML", "TypeScript", "Vector mathematics", " Sensor fusion", "Automatic PDF generation"],
    spotlight: true,
  },
];

// -----------------------------------------------------------------------------
// PREVIEWS  (curation config — was the top half of data/previews.ts)
// -----------------------------------------------------------------------------
// The one place that decides *what* the homepage previews. The content catalogs
// (data/photos.ts, the projects above) are the full libraries; this names, by
// stable id, which items each homepage surface shows — and in what order.
// The resolver functions that turn this into ready-to-render data stay in
// data/previews.ts (they read the photos/projects catalogs); this is just the
// curation a person edits.
//
// Every pick references content by a stable id (photo `code`, project `title`).
// If an id doesn't match anything in the catalog it is simply skipped — a typo
// degrades gracefully (that tile drops out) rather than breaking the build.
//
// Each visual pick may also carry a `previewImage` override so a homepage
// preview can differ from the content's own first image.

/** A photo pick: a photo `code`, plus an optional image override. */
export type PhotoPick = {
  /** stable photo `code` from data/photos.ts, e.g. "0013" */
  code: string;
  /** optional /public image path to show instead of the photo's own thumb */
  previewImage?: string;
};

/** A design pick: a project `title`, plus an optional cover override. */
export type DesignPick = {
  /** exact project `title` from data/projects-design.ts */
  title: string;
  /** optional /public image path to show instead of the project's slide 1 */
  previewImage?: string;
};

/** A carousel pick: a web-project `title` + which browser-window skin to use. */
export type CarouselPick = {
  /** exact project `title` from data/projects-web.ts */
  title: string;
  /** browser-window skin class (see `.shot` variants in globals.css) */
  variant: "s-acie" | "s-dark" | "s-warm" | "s-lav" | "s-mint";
};

export type PreviewConfig = {
  photographyBento: PhotoPick[];
  graphicDesignBento: DesignPick[];
  /** the "Right now" highlight photo, named by `code` (see rightNowPhoto below) */
  rightNowPhoto: string;
  digitalHomeCarousel: CarouselPick[];
  workBands: string[];
};

export const previews: PreviewConfig = {
  // CUSTOMIZE: Photography bento — the 4 (or N) photos shown in the "More than
  // code" photography card, in order. Codes come from data/photos.ts.
  // (Film-strip Frames like Longs Peak are skipped here — a square crop clips
  // their baked border.) A `previewImage` may override any tile's thumb.
  photographyBento: [
    { code: "0001" },
    { code: "0013" },
    { code: "0030" },
    { code: "0004" },
  ],

  // CUSTOMIZE: Graphic-design bento — which design projects appear, in order.
  // Default shows each project's slide 1; set `previewImage` to show a custom
  // cover instead.
  graphicDesignBento: [
    { title: "Notion Brand Pitch" },
    { title: "Spotify IMC Campaign" },
    { title: "Photography Presentation UI" },
  ],

  // CUSTOMIZE: "Right now" highlight photo — named directly by its `code` from
  // data/photos.ts. (This card is driven entirely from here now; the `featured`
  // flag in photos.ts no longer decides it.)
  rightNowPhoto: "0055",

  // CUSTOMIZE: Digital-home carousel — which projects tour, in order, and the
  // browser-window skin for each. Titles come from data/projects-web.ts.
  digitalHomeCarousel: [
    { title: "Ostiara", variant: "s-acie" },
    { title: "MyLifeInARepo", variant: "s-dark" },
    { title: "Querryn", variant: "s-warm" },
    { title: "VaultDNA", variant: "s-lav" },
    { title: "charlieramus.com", variant: "s-mint" },
    { title: "Backtrace", variant: "s-dark" },
  ],

  // CUSTOMIZE: Work bands — the curated projects (in order) for the "Tiny
  // fraction of my work" section. The homepage renders exactly 4 bespoke band
  // visuals, so keep this at 4 titles; extras beyond 4 are ignored.
  workBands: ["Ostiara", "MyLifeInARepo", "charlieramus.com", "VaultDNA"],
};

// -----------------------------------------------------------------------------
// DECORATION  (V10 — per-surface decorative motion, config-driven)
// -----------------------------------------------------------------------------
// A flagship surface gets a signature decorative idea, fully editable here and
// motion-safe (removed / frozen under reduced motion):
//   • writingSpirals — rotating Archimedean-spiral quote text in the /writing
//     margins (desktop-only). components/spiral-text.tsx renders each entry.

/** One spiral quote laid down beside the /writing reading column. Decorative —
 *  desktop-only, removed entirely under prefers-reduced-motion. Every field but
 *  `text` is a placement knob you can freely play with:
 *    • side  — which side of the column it sits on
 *    • size  — "xs" (tiny) · "sm" · "md" · "lg"
 *    • place — "inner" sits it INSIDE the reading column, closer to the centre
 *              (it rides behind the text, which always stays on top),
 *              "edge" tucks it right up against the text,
 *              "gutter" sits it out in the margin (fully revealed),
 *              "bleed" lets it hang off the page edge as pure texture.
 *              Defaults to "gutter".
 *    • top   — vertical position down the page as a CSS length (e.g. "18%"). */
export type WritingSpiral = {
  text: string;
  side: "left" | "right";
  size?: "xs" | "sm" | "md" | "lg";
  place?: "inner" | "edge" | "gutter" | "bleed";
  top?: string;
};

// CUSTOMIZE: the spiral quotes + where each one lands. Pulled from Charlie's
// essays + the closing line. Mix sizes/places/sides freely — reuse a line at a
// different size if you like. They render black (same ink as the body text).
export const writingSpirals: WritingSpiral[] = [
  {
    text: "A portfolio is not proof of what you built. It is proof you noticed.",
    side: "right",
    size: "md",
    place: "inner",
    top: "4%",
  },
  {
    text: "Got tired of uneven things. The city. People wanting more than they need.",
    side: "left",
    size: "sm",
    place: "edge",
    top: "22%",
  },
  {
    text: "The moment you can explain why a hobby is good for you, you have already started to kill it.",
    side: "left",
    size: "md",
    place: "inner",
    top: "48%",
  },
  {
    text: "The bigger the model, the more confidently it reflects whoever dominated the data it learned from.",
    side: "right",
    size: "sm",
    place: "edge",
    top: "40%",
  },
  {
    text: "It is proof you noticed.",
    side: "right",
    size: "xs",
    place: "gutter",
    top: "72%",
  },
  {
    text: "Got tired of uneven things.",
    side: "left",
    size: "xs",
    place: "gutter",
    top: "68%",
  },
];

/** One segment of the vertical `/photography` marquee. `color` resolves to a
 *  theme token (`--color-cyan` / `--color-red` / `--color-yellow`); `text` is
 *  the tagline. Bold Inter, decorative — frozen under prefers-reduced-motion. */
export type Marquee = {
  color: "cyan" | "red" | "yellow";
  text: string;
};

// CUSTOMIZE: play with the words and colors — one segment per turquoise / red /
// yellow. Keep them about the photography (this rail lives on /photography).
export const marquees: Marquee[] = [
  { color: "cyan", text: ".FRAME.SHOOT." },
  { color: "red", text: ".CHASE.LIGHT." },
  { color: "yellow", text: ".ROAM.CAPTURE." },
];

// -----------------------------------------------------------------------------
// SECTION COPY  (folded in from components + pages, V9 Stage 2)
// -----------------------------------------------------------------------------
// The headings, sublines, nav labels and page ledes that used to be hardcoded
// inline in JSX. Each component/page now reads its string from here, so all the
// editable prose finally lives in this one file. Moved character-for-character —
// the site renders identically. Edit the copy here; the components don't change.

export const sections = {
  // components/hero.tsx — primary nav (homepage anchors). Each item is a
  // { label, href } pair; href is a "#anchor" on the homepage or an inner route.
  // CUSTOMIZE: nav labels + hrefs.
  nav: [
    { label: "work", href: "#work" },
    { label: "photography", href: "/photography" },
    { label: "about", href: "#about" },
  ],

  // components/personal-bento.tsx — the "More than code" section.
  personalBento: {
    // CUSTOMIZE: section title (Charlie: "More than code", may change)
    title: "More than code",
    // CUSTOMIZE: section subline
    subline:
      "Where I've worked, the essays I write, photography, and the design work, everything beyond the code.",
    // CUSTOMIZE: career-timeline caption
    careerNote: "Solo builds & side work",
    // CUSTOMIZE: graphic-design card title
    graphicTitle: "Brand & layout",
  },

  // components/about.tsx — the "Behind the pixels" section.
  about: {
    // CUSTOMIZE: about subline
    subline:
      "The person behind the stuff you see, where I'm based, what I care about, and how I like to work.",
  },

  // components/work.tsx — the "Tiny fraction of my work" section.
  work: {
    // CUSTOMIZE: work subline
    subline:
      "A few things I've built solo, end to end, from the backend and data model to the design system and the copy.",
  },

  // components/right-now.tsx — the "Right now" section.
  rightNow: {
    // CUSTOMIZE: section heading
    title: "Right now",
    // CUSTOMIZE: section subline
    subline:
      "A quick pulse on what's fresh, the active build, the open journal, and the latest essay.",
  },

  // components/petal-simon.tsx — the Playground game card.
  petalSimon: {
    // CUSTOMIZE: playground kicker
    kicker: "I need something to fill here",
    // CUSTOMIZE: game card title
    title: "Petal Simon",
  },

  // The inner pages — each has a kicker, an <h1> heading, and a lede paragraph.
  pages: {
    // app/design/page.tsx
    design: {
      kicker: "Design",
      // CUSTOMIZE: heading + lede
      heading: "Brand & layout",
      lede:
        "Pitches, campaigns and editorial UI. Where the argument is carried as much by type and image as by words. Produced in Figma.",
    },
    // app/gear/page.tsx
    gear: {
      kicker: "Gear",
      // CUSTOMIZE: heading + lede
      heading: "What's in the bag",
      lede:
        "The kit behind the photography! a Canon EOS R5 body, a DJI Air 2s in the air, and the glass and bags that travel with them. (Some of these are discontinued but a quick google search will reveal their successors.)",
    },
    // app/photography/page.tsx — `{count}` is replaced with the live photo count.
    photography: {
      kicker: "Photography",
      // CUSTOMIZE: gallery heading + lede ({count} = number of photos)
      heading: "Frames from the road",
      lede:
        "{count} frames from the road. Iceland, the Colorado Rockies, the British Virgin Islands and wherever the light's good. Tap any photo to open it.",
    },
    // app/web-projects/page.tsx
    webProjects: {
      kicker: "Web Projects",
      // CUSTOMIZE: heading + lede
      heading: "Things I've built",
      lede:
        "Sites, apps and extensions, designed and shipped solo, from the backend to the last pixel.",
    },
    // app/writing/page.tsx — `heading` renders the "&" as-is (React escapes it);
    // `metaDescription` is the <meta> description for the /writing index.
    writing: {
      kicker: "Writing",
      // CUSTOMIZE: heading + lede + metaDescription
      heading: "Essays & stories",
      lede:
        "Long-form pieces — arguments I've talked myself into, and one I made up entirely.",
      metaDescription:
        "Essays and stories by Charlie Ramus — on optimization, machine learning, morality, and the occasional lighthouse.",
    },
  },
} as const;
