// AUTO-GENERATED by scripts/sync-gallery.mjs — do not edit directly.
// Drop photos into public/photos/trips/<Trip Name>/, then run: npm run sync-gallery
//
// The folder-driven "By trip" dataset (V15). Each subdir of public/photos/trips/
// is a trip; the folder name is the section title. No captions — the sticky
// print-reference `code` (see public/photos/numbers.json) is the only label.

export type TripPhoto = {
  /** full-res image path in /public */
  src: string;
  /** thumbnail path */
  thumb: string;
  /** alt text — trip name + the photo's number (there is no caption) */
  alt: string;
  /** intrinsic aspect ratio, width / height (drives masonry sizing) */
  ratio: number;
  /** sticky global print-reference number */
  code: string;
  /** base64 blur placeholder for next/image */
  blurDataURL?: string;
};

export const tripPhotoGroups: { title: string; photos: TripPhoto[] }[] = [];
